### PR TITLE
add me cos i helped fix things

### PR DESCRIPTION
**Pull request by SuperEvilLuke**

### CODE REVIEW

**Comment by Cyteon** [comment]
You have done nothing on the repo, what have you fixed?

**Comment by SuperEvilLuke** [comment]
i did a lvie share with tara, so i didnt coem up on the repo

**Review by ninsaccplayzyt — CHANGES_REQUESTED** [review]
move the Luke name back to where all the other ones are, like the users one

**Review by ninsaccplayzyt — APPROVED** [review]
Perfect

**Pull request merged**
